# Add all required application properties for the Atomic BC module here
# Read the root README.md for more information.

bc.qualifier=${BC_QUALIFIER:audit_log}
server.port=${SERVER_PORT:9444}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga, consent-saga, anonymize-saga}
spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/${CERTIFICATE_FILENAME:audit-log.p12}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000

