-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS instructor (
    id BINARY(16) NOT NULL PRIMARY KEY,
    person_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
