# Add any BC-specific properties here. These can be overridden by environment variables or command-line arguments.

bc.qualifier=${BC_QUALIFIER:person}
server.port=${SERVER_PORT:9452}
# comma separated list of handlers/sagas that are allowed to call /internal/** endpoints on this BC
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga, anonymize-saga, message-person, person-notification}
spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/${CERTIFICATE_FILENAME:person.p12}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true
