#DB identifiers
db.name=${DB_NAME:sopinfo_${bc.qualifier}_db}
db.port=${DB_PORT:3306}
db.base-url=${DB_URL:jdbc:mariadb}
spring.jpa.enabled=${SPRING_JPA_ENABLED:false}
spring.datasource.url=${db.base-url}://${DB_HOST:localhost}:${db.port}/${db.name}
spring.datasource.username=${DB_USERNAME:${bc.qualifier}}
spring.datasource.password=${DB_PASSWORD:${bc.qualifier}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:false}
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=${PREFERRED_UUID_JDBC_TYPE:BINARY}

