-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS consent_statement (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    statement_text VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS consent (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    person_reference BINARY(16) NOT NULL,
    consent_statement_id BINARY(16) NOT NULL,
    status VARCHAR(255) NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    CONSTRAINT fk_consent_consent_statement_id FOREIGN KEY (consent_statement_id) REFERENCES consent_statement(id),
    CONSTRAINT uk_consent_person_reference_consent_statement_id UNIQUE (person_reference, consent_statement_id)
);
