# Add all required application properties for the Atomic BC module here
# Read the root README.md for more information.

# Generic base identifiers
bc.qualifier=${BC_QUALIFIER:sop_education}
server.port=${SERVER_PORT:9461}

# ---------- Downstream base URLs ----------
 # mTLS
education.base-url=${EDUCATION_BASE_URL:https://bc-education.sop.local:9459}
sop.base-url=${SOP_BASE_URL:https://bc-sop.sop.local:9453}
mtls.enabled=${MTLS_ENABLED:true}

# comma separated list of handlers/sagas that are allowed to call /internal/** endpoints on this BC
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga}
spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/${CERTIFICATE_FILENAME:sop-education.p12}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

#compositekey validation required
compositekey.validate.enabled=${COMPOSITE_KEY_VALIDATE_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000

