# Add all required application properties for the Atomic BC module here
# Read the root README.md for more information.

bc.qualifier=${BC_QUALIFIER:education_instructor}
server.port=${SERVER_PORT:9457}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:ssl,jpa,shared}
security.enabled=${SECURITY_ENABLED:true}

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true

# TLS configuration
spring.ssl.bundle.jks.app.keystore.location=file:${TLS_DIR:Y:/SOP-info}/education-instructor.p12

# Composite Key Validation
compositekey.validate.enabled=${COMPOSITE_KEY_VALIDATE_ENABLED:true}
