-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-09-03T13:10:43Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS consent_saga_lock (
    sessionId BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(255) NOT NULL,
    lockedAt DATETIME NOT NULL
);
