-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS message (
    id BINARY(16) NOT NULL PRIMARY KEY,
    date_time_sent DATETIME(6) NOT NULL,
    message_text VARCHAR(4000) NOT NULL,
    sender_person_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
