-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-06-01T10:18:38Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS person_notification (
    person_ref BINARY(16) NOT NULL,
    notification_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (person_ref, notification_ref)
);
