# Add all required application properties for the Atomic BC module here
# Read the root README.md for more information.

# Generic base identifiers
bc.qualifier=${BC_QUALIFIER:organisation}
server.port=${SERVER_PORT:9451}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:gw-common, registration-saga}
spring.profiles.active=ssl,jpa,shared
security.enabled=${SECURITY_ENABLED:true}

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true