# Add all required application properties for the Atomic BC module here
# Read the root README.md for more information.

bc.qualifier=${BC_QUALIFIER:education_line}
server.port=${SERVER_PORT:9446}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga, education-line-saga}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000


# TLS configuration
spring.ssl.bundle.jks.app.keystore.location=file:${TLS_DIR:Y:/SOP-info}/education-line.p12
