-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS education (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL
);
