bc.qualifier=${BC_QUALIFIER:anonymize-saga}
server.port=${SERVER_PORT:8348}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:consent-handler}

# ---------- Downstream base URLs ----------
 # mTLS
person.base-url=${PERSON_BASE_URL:https://bc-person.sop.local:9452}
anonymize.base-url=${ANONYMIZE_BASE_URL:https://bc-anonymize.sop.local:9499}
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}


security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000
