bc.qualifier=${BC_QUALIFIER:education-line-saga}
server.port=${SERVER_PORT:8346}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:education-line-handler}

# ---------- Downstream base URLs ----------
 # mTLS
education-line.base-url=${EDUCATION_LINE_BASE_URL:https://bc-education-line.sop.local:9446}
education.base-url=${EDUCATION_BASE_URL:https://bc-education.sop.local:9459}
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}

security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000
