# Add any BC-specific properties here. These can be overridden by environment variables or command-line arguments.

bc.qualifier=${BC_QUALIFIER:instructor}
server.port=${SERVER_PORT:9448}
# comma separated list of handlers/sagas that are allowed to call /internal/** endpoints on this BC
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga, sop-instructor, education-instructor}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
spring.autoconfigure.exclude=${SPRING_AUTOCONFIGURE_EXCLUDE:}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000

