-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-09-03T13:10:43Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS sop (
    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    education VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
