-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-09-03T13:10:43Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS education_line (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    duration_years INT NOT NULL,
    duration_months INT NOT NULL,
    duration_days INT NOT NULL,
    education_ref BINARY(16) NOT NULL,
    is_active BOOLEAN NOT NULL
);
