-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-08T06:20:40Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS notification (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    message_ref BINARY(16) NOT NULL,
    seen BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL
);
