bc.qualifier=${BC_QUALIFIER:consent-saga}
server.port=${SERVER_PORT:8343}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:consent-handler, registration-saga}

# ---------- Downstream base URLs ----------
 # mTLS
consent.base-url=${CONSENT_BASE_URL:https://bc-consent.sop.local:9445}
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}


security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

