#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./infra/scripts/gen-manifest.sh > manifest.yml
#
# Must be run from $PROJECT_ROOT (repo root).
# Generates a manifest.yml listing all microservices pushed to the registry,
# the total count, and the image tag used.
#
# Optional env:
#   REGISTRY_IMAGE  (default: local)
#   IMAGE_TAG       (default: dev)
#   SEARCH_DEPTH    (default: 3)

REGISTRY_IMAGE="${REGISTRY_IMAGE:-local}"
IMAGE_TAG="${IMAGE_TAG:-dev}"
SEARCH_DEPTH="${SEARCH_DEPTH:-3}"
GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

services=()

for bc in bc-*/; do
    [[ -d "$bc" ]] || continue

    dockerfile_path="$(find "$bc" -maxdepth "$SEARCH_DEPTH" -type f -name Dockerfile | sort | head -n 1 || true)"
    [[ -n "$dockerfile_path" ]] || continue

    svc="${bc%/}"
    svc="${svc#bc-}"
    services+=("$svc")
done

count="${#services[@]}"

cat <<YAML
# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by infra/scripts/gen-manifest.sh

manifest:
  generated_at: "${GENERATED_AT}"
  image_tag: "${IMAGE_TAG}"
  registry: "${REGISTRY_IMAGE}"
  total_services: ${count}
  services:
YAML

for svc in "${services[@]}"; do
    echo "    - name: ${svc}"
    echo "      image: ${REGISTRY_IMAGE}/${svc}-service:${IMAGE_TAG}"
done