#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./infra/scripts/gen-db-provision.sh > db-create.sql
#   ./infra/scripts/gen-db-provision.sh [--write-file]
#
# Scans all bc-* directories for a Dockerfile (same logic as gen-compose.sh).
# For each BC found, reads bc.qualifier from its application.properties
# to generate SQL that creates databases and users.
#
# Only BCs that contain @Entity annotations are included — stub BCs and
# API-only modules do not get a database.
#
# By default, SQL is printed to stdout so it can be redirected:
#   ./infra/scripts/gen-db-provision.sh > db-create.sql
#
# Options:
#   --write-file   Write to infra/db/provision/00-create-dbs.generated.sql instead of stdout
#
# Optional env:
#   PROJECT_NAME         (default: DWH)          MUST match gen-compose.sh's
#                                                default exactly — see below.
#   DB_PASSWORD_SUFFIX  (default: localdev)      ditto.
#
# Must be run from the repo root (where bc-* folders live).
#
# IMPORTANT — gen-compose.sh independently derives each BC's DB_NAME/
# DB_USER/DB_PASSWORD to inject into that BC's container environment,
# using this exact same derivation (qualifier resolution, prefix,
# password suffix). Neither script reads the other's output — they
# only agree because the algorithm and defaults are kept identical in
# both places. If you change the naming/password scheme here, the
# same change has to be made in gen-compose.sh's has_db block, or the
# containers will be provisioned against credentials that don't match
# what the database actually has.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_FILE="$REPO_ROOT/infra/db/provision/00-create-dbs.generated.sql"

WRITE_FILE=false
for arg in "$@"; do
    [[ "$arg" == "--write-file" ]] && WRITE_FILE=true
done

SEARCH_DEPTH="${SEARCH_DEPTH:-3}"
PROJECT_NAME="${PROJECT_NAME:-DWH}"
DB_PASSWORD_SUFFIX="${DB_PASSWORD_SUFFIX:-localdev}"

# ── helpers ────────────────────────────────────────────────────────────────────

find_dockerfile() {
    find "$1" -maxdepth "$SEARCH_DEPTH" -type f -name Dockerfile | sort | head -n 1 || true
}

find_app_props() {
    find "$1" -maxdepth 6 -type f -name application.properties 2>/dev/null | sort | head -n 1 || true
}

# Extract the default value from a property like:
#   bc.qualifier=${BC_QUALIFIER:person}  →  person
extract_default() {
    local props="$1" key="$2"
    [[ -f "$props" ]] || return 0
    local line
    line="$(grep -E "^[[:space:]]*${key}[[:space:]]*=" "$props" | head -n 1 | tr -d '\r' || true)"
    [[ -n "$line" ]] || return 0
    local val
    val="$(echo "$line" | sed -nE 's/.*\$\{[^:}]+:([^}]+)\}.*/\1/p')"
    if [[ -z "$val" ]]; then
        val="$(echo "$line" | sed -nE 's/^[^=]+=\s*(.*)/\1/p' | tr -d ' ')"
    fi
    echo "$val"
}

# Returns 0 (true) if the BC contains any @Entity annotation in its Java sources
bc_has_entities() {
    local bc_dir="$1"
    grep -rl "@Entity" "$bc_dir" \
        --include="*.java" \
        --exclude-dir=target \
        --exclude-dir=".git" \
        2>/dev/null | grep -q .
}

# ── generate SQL ───────────────────────────────────────────────────────────────

generate() {
    echo "-- AUTO-GENERATED FILE. DO NOT EDIT."
    echo "-- Generated by infra/scripts/gen-db-provision.sh"
    echo "-- Run: ./infra/scripts/gen-db-provision.sh > db-create.sql"
    echo "-- Only BCs containing @Entity annotations are included."
    echo "--"
    echo "-- LOCAL DEV ONLY: usernames/passwords here are deterministic"
    echo "-- and predictable by design (see DB_PASSWORD_SUFFIX above) so"
    echo "-- this file and gen-compose.sh's injected env vars always"
    echo "-- agree without any shared state. Do not point this at"
    echo "-- anything beyond a disposable local MariaDB instance."
    echo ""

    cd "$REPO_ROOT"

    for bc in bc-*/; do
        bc="${bc%/}"
        [[ -d "$bc" ]] || continue

        dockerfile="$(find_dockerfile "$bc")"
        [[ -n "$dockerfile" ]] || continue

        # Skip BCs with no JPA entities — they don't need a database
        if ! bc_has_entities "$bc"; then
            continue
        fi

        props="$(find_app_props "$bc")"

        qualifier=""
        if [[ -n "$props" ]]; then
            qualifier="$(extract_default "$props" "bc.qualifier")"
        fi
        if [[ -z "$qualifier" ]]; then
            qualifier="${bc#bc-}"
        fi

        db_name="${PROJECT_NAME}_${qualifier}_db"
        db_user="$qualifier"
        db_pass="${qualifier}_${DB_PASSWORD_SUFFIX}"

        echo "-- $bc  ($(dirname "$dockerfile"))"
        echo "CREATE DATABASE IF NOT EXISTS ${db_name}"
        echo "  CHARACTER SET utf8mb4"
        echo "  COLLATE utf8mb4_unicode_ci;"
        echo ""
        echo "CREATE USER IF NOT EXISTS '${db_user}'@'%' IDENTIFIED BY '${db_pass}';"
        echo "GRANT ALL PRIVILEGES ON ${db_name}.* TO '${db_user}'@'%';"
        echo "FLUSH PRIVILEGES;"
        echo ""
    done
}

# ── output ─────────────────────────────────────────────────────────────────────

if $WRITE_FILE; then
    mkdir -p "$(dirname "$OUT_FILE")"
    generate > "$OUT_FILE"
    echo "Written: $OUT_FILE" >&2
    echo "" >&2
    grep '^-- bc-' "$OUT_FILE" | sed 's/^-- /  /' >&2 || true
else
    generate
fi