bc.qualifier=${BC_QUALIFIER:login-saga}
server.port=${SERVER_PORT:8344}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:login-handler}

# ---------- Downstream base URLs ----------
 # mTLS
login.base-url=${LOGIN_BASE_URL:https://bc-login.sop.local:9455}
consent.base-url=${CONSENT_BASE_URL:https://bc-consent.sop.local:9456}
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}
instructor.base-url=${INSTRUCTOR_BASE_URL:https://bc-instructor.sop.local:9448}
apprentice.base-url=${APPRENTICE_BASE_URL:https://bc-apprentice.sop.local:9443}


security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000
