-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-09-03T13:18:34Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS logins (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    person_ref BINARY(16) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    is_activated BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS login_sessions (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    login_id BINARY(16) NOT NULL,
    session_token VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT fk_login_sessions_login_id FOREIGN KEY (login_id) REFERENCES logins(id)
);
