-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS person (
    id BINARY(16) NOT NULL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    organization_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phone_numbers (
    id BINARY(16) NOT NULL PRIMARY KEY,
    person_id BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    phone_user_type VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    CONSTRAINT fk_phone_numbers_person_id FOREIGN KEY (person_id) REFERENCES person(id)
);
