bc.qualifier=${BC_QUALIFIER:gateway_common}
server.port=${SERVER_PORT:10459}

# Internal mTLS configuration
registration-saga.base-url=${REGISTRATION_SAGA_BASE_URL:http://bc-registration-saga.sop.local:8345}
sop.base-url=${SOP_BASE_URL:http://bc-sop.sop.local:9453}
organisation.base-url=${ORGANISATION_BASE_URL:http://bc-organisation.sop.local:9451}

mtls.enabled=${MTLS_ENABLED:true}

internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:TBD}
security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true

# TLS configuration
spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/${CERTIFICATE_FILENAME:gateway-common.p12}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000