-- AUTO-GENERATED FILE. DO NOT EDIT.
-- Generated by infra/scripts/gen-db-provision.sh
-- Run: ./infra/scripts/gen-db-provision.sh

-- bc-apprentice  (bc-apprentice/apprentice-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_apprentice_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'apprentice'@'%' IDENTIFIED BY 'apprentice';
GRANT ALL PRIVILEGES ON sopinfo_apprentice_db.* TO 'apprentice'@'%';
FLUSH PRIVILEGES;

-- bc-audit-log  (bc-audit-log/audit-log-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_audit_log_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'audit_log'@'%' IDENTIFIED BY 'audit_log';
GRANT ALL PRIVILEGES ON sopinfo_audit_log_db.* TO 'audit_log'@'%';
FLUSH PRIVILEGES;

-- bc-auth_handler  (bc-auth_handler/auth_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_auth_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'auth_handler'@'%' IDENTIFIED BY 'auth_handler';
GRANT ALL PRIVILEGES ON sopinfo_auth_handler_db.* TO 'auth_handler'@'%';
FLUSH PRIVILEGES;

-- bc-check_in_handler  (bc-check_in_handler/check_in_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_check_in_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'check_in_handler'@'%' IDENTIFIED BY 'check_in_handler';
GRANT ALL PRIVILEGES ON sopinfo_check_in_handler_db.* TO 'check_in_handler'@'%';
FLUSH PRIVILEGES;

-- bc-communication_handler  (bc-communication_handler/communication_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_communication_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'communication_handler'@'%' IDENTIFIED BY 'communication_handler';
GRANT ALL PRIVILEGES ON sopinfo_communication_handler_db.* TO 'communication_handler'@'%';
FLUSH PRIVILEGES;

-- bc-consent  (bc-consent/consent-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_consent_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'consent'@'%' IDENTIFIED BY 'consent';
GRANT ALL PRIVILEGES ON sopinfo_consent_db.* TO 'consent'@'%';
FLUSH PRIVILEGES;

-- bc-education_line  (bc-education_line/education_line-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_education_line_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'education_line'@'%' IDENTIFIED BY 'education_line';
GRANT ALL PRIVILEGES ON sopinfo_education_line_db.* TO 'education_line'@'%';
FLUSH PRIVILEGES;

-- bc-institution  (bc-institution/institution-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_institution_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'institution'@'%' IDENTIFIED BY 'institution';
GRANT ALL PRIVILEGES ON sopinfo_institution_db.* TO 'institution'@'%';
FLUSH PRIVILEGES;

-- bc-instructor  (bc-instructor/instructor-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_instructor_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'instructor'@'%' IDENTIFIED BY 'instructor';
GRANT ALL PRIVILEGES ON sopinfo_instructor_db.* TO 'instructor'@'%';
FLUSH PRIVILEGES;

-- bc-message  (bc-message/message-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_message_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'message'@'%' IDENTIFIED BY 'message';
GRANT ALL PRIVILEGES ON sopinfo_message_db.* TO 'message'@'%';
FLUSH PRIVILEGES;

-- bc-notification  (bc-notification/notification-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_notification_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'notification'@'%' IDENTIFIED BY 'notification';
GRANT ALL PRIVILEGES ON sopinfo_notification_db.* TO 'notification'@'%';
FLUSH PRIVILEGES;

-- bc-organisation  (bc-organisation/organisation-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_organisation_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'organisation'@'%' IDENTIFIED BY 'organisation';
GRANT ALL PRIVILEGES ON sopinfo_organisation_db.* TO 'organisation'@'%';
FLUSH PRIVILEGES;

-- bc-organisation_handler  (bc-organisation_handler/organisation_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_organisation_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'organisation_handler'@'%' IDENTIFIED BY 'organisation_handler';
GRANT ALL PRIVILEGES ON sopinfo_organisation_handler_db.* TO 'organisation_handler'@'%';
FLUSH PRIVILEGES;

-- bc-person  (bc-person/person-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_person_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'person'@'%' IDENTIFIED BY 'person';
GRANT ALL PRIVILEGES ON sopinfo_person_db.* TO 'person'@'%';
FLUSH PRIVILEGES;

-- bc-sop  (bc-sop/sop-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_sop_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'sop'@'%' IDENTIFIED BY 'sop';
GRANT ALL PRIVILEGES ON sopinfo_sop_db.* TO 'sop'@'%';
FLUSH PRIVILEGES;

-- bc-sop_handler  (bc-sop_handler/sop_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_sop_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'sop_handler'@'%' IDENTIFIED BY 'sop_handler';
GRANT ALL PRIVILEGES ON sopinfo_sop_handler_db.* TO 'sop_handler'@'%';
FLUSH PRIVILEGES;

-- bc-user_handler  (bc-user_handler/user_handler-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_user_handler_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'user_handler'@'%' IDENTIFIED BY 'user_handler';
GRANT ALL PRIVILEGES ON sopinfo_user_handler_db.* TO 'user_handler'@'%';
FLUSH PRIVILEGES;

-- bc-work-hour  (bc-work-hour/work-hour-impl)
CREATE DATABASE IF NOT EXISTS sopinfo_work_hour_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'work_hour'@'%' IDENTIFIED BY 'work_hour';
GRANT ALL PRIVILEGES ON sopinfo_work_hour_db.* TO 'work_hour'@'%';
FLUSH PRIVILEGES;

