-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-09-03T13:10:43Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS audit_log (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    actor_type ENUM('service','system','user') NOT NULL,
    actor_ref BINARY(16) NOT NULL,
    origin_system VARCHAR(255) NOT NULL,
    origin_service VARCHAR(255) NOT NULL,
    origin_component VARCHAR(255) NOT NULL,
    severity ENUM('info','debug','low','medium','high') NOT NULL,
    data VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
