# Generic base identifiers
fqdn.package=${FQDN_PACKAGE:local.sop.sopinfo}
spring.application.name=${APP_NAME:${bc.qualifier}-service}
server.address=${SERVER_ADDRESS:0.0.0.0}

# Logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.group.bc=${fqdn.package}.${bc.qualifier}
logging.level.bc=${LOGGING_LEVEL:DEBUG}
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true


