bc.qualifier=${BC_QUALIFIER:message-saga}
server.port=${SERVER_PORT:8349}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:message-handler}

# ---------- Downstream base URLs ----------
 # mTLS

apprentice.base-url=${APPRENTICE_BASE_URL:https://bc-apprentice.sop.local:9443} 
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}
educationline.base-url=${EDUCATIONLINE_BASE_URL:https://bc-educationline.sop.local:9446}
instructor.base-url=${INSTRUCTOR_BASE_URL:https://bc-instructor.sop.local:9448}
message.base-url=${MESSAGE_BASE_URL:https://bc-message.sop.local:9449}
notification.base-url=${NOTIFICATION_BASE_URL:https://bc-notification.sop.local:9450}
messageperson.base-url=${MESSAGEPERSON_BASE_URL:https://bc-messageperson.sop.local:9456}
personnotification.base-url=${PERSONNOTIFICATION_BASE_URL:https://bc-personnotification.sop.local:9460}
educationinstructor.base-url=${EDUCATIONINSTRUCTOR_BASE_URL:https://bc-educationinstructor.sop.local:9457}
person.base-url=${PERSON_BASE_URL:https://bc-person.sop.local:9452}


security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000

# SOPINFO Core Logging Auto-Configuration
sopinfo.core.logging.enabled=true
sopinfo.core.logging.console.error-only=true
sopinfo.core.logging.file.enabled=true
sopinfo.core.logging.file.use-service-name=true