@startuml Common Web Class Diagram
top to bottom direction
title Common Web Class Diagram
skinparam packageStyle rectangle
skinparam Shadowing false
skinparam classFontSize 12
skinparam classFontName Arial
skinparam WrapWidth 260
skinparam ComponentStyle uml2

' common web folders = LightGreen

folder "local.sop.sopinfo.infrastructure" #LightGreen {
    package "config" {
        class WebConfig <<@Configuration implements WebMvcConfigurer>> {
            + addResourceHandlers(registry: ResourceHandlerRegistry): void
        }
    }
    package "exception" {
        class EndpointExceptionHandler <<@RestControllerAdvice>> {
            + onDomain(ex: DomainException, locale: Locale) : ProblemDetail
            + onMethodArgNotValid(ex: MethodArgumentNotValidException, locale: Locale) : ProblemDetail
            + onBind(ex: BindException, req: HttpServletRequest) : ProblemDetail
            + onParamValidation(ex: ConstraintViolationException, locale: Locale): ProblemDetail
            + onMissingParam(ex: MissingServletRequestParameterException, locale: Locale): ProblemDetail
            + onTypeMisMatch(ex: MethodArgumentTypeMismatchException, req: HttpServletRequest): ProblemDetail
            + onDataIntegrity(ex: DataIntegrityViolationException, locale: Locale): ProblemDetail
            + onNotReadable: HttpMessageNotReadableException, req: HttpServletRequest): ProbemDetail
            + onNoHandlerFound(ex: NoHandlerFoundException, req: HttpServletRequest): ProbemDetail
            + onNoResourceFound(ex: NoResourceFoundException, req: HttpServletRequest): ProbemDetail
            + onAny(ex: Exception, locale: Locale): ProblemDetail
        }
        class CommonWebAutoConfiguration <<AutoConfiguration>> {}
    }
    package "health" {
         class CommonWebHealthIndicator <<implements HealthIndicator>> {
            + init(): void <<@PostConstruct>>
            + health(): Health
            + getHandlerCount() : integer
            + getHandlerNames() : List<String>

        }
    }
    package "i18n" {
        class I18nAutoConfiguration <<AutoConfiguration>> {
            + messageSource: MessageSource <<@Bean>> <<@Primary>>
            + localeResolver(): LocaleResolver <<@Bean>>
        }
        class SafeAcceptHeaderLocaleResolver {
            + resolveLocale(request: HttpServletRequest): Locale
        }
    }

}

@enduml