-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-05T10:09:57Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS message_person (
    message_ref BINARY(16) NOT NULL,
    person_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (message_ref, person_ref)
);
