-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-06-02T10:17:51Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS education_saga_lock (
    sessionId BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(255) NOT NULL,
    lockedAt DATETIME NOT NULL
);
