-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-04T12:42:32Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS work_hour_schedule (
    id BINARY(16) NOT NULL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    start_time VARCHAR(255) NOT NULL,
    end_time VARCHAR(255) NOT NULL,
    week_day VARCHAR(255) NOT NULL,
    sop_id BINARY(16) NOT NULL
);
