bc.qualifier=${BC_QUALIFIER:anonymize}
server.port=${SERVER_PORT:9499}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-saga, anonymize-saga}

security.enabled=${SECURITY_ENABLED:true}
server.ssl.enabled=${SERVER_SSL_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000
