-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-06-18T09:44:44Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS education_instructor (
    education_ref BINARY(16) NOT NULL,
    instructor_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (education_ref, instructor_ref)
);
