bc.qualifier=${BC_QUALIFIER:registration-saga}
server.port=${SERVER_PORT:8345}
internal.mtls.allowed-callers=${INTERNAL_MTLS_ALLOWLIST:registration-handler}

# ---------- Downstream base URLs ----------
 # mTLS
apprentice.base-url=${APPRENTICE_BASE_URL:https://bc-apprentice.sop.local:9443} 
auditlog.base-url=${AUDITLOG_BASE_URL:https://bc-auditlog.sop.local:9444}
consent.base-url=${CONSENT_SAGA_BASE_URL:https://bc-consent.sop.local:9445}
consent-saga.base-url=${CONSENT_SAGA_BASE_URL:https://bc-consent-saga.sop.local:8343}
educationline.base-url=${EDUCATIONLINE_BASE_URL:https://bc-educationline.sop.local:9446}
instructor.base-url=${INSTRUCTOR_BASE_URL:https://bc-instructor.sop.local:9448}
login.base-url=${LOGIN_BASE_URL:https://bc-login.sop.local:9455}
organization.base-url=${ORGANIZATION_BASE_URL:https://bc-organization.sop.local:9451} 
person.base-url=${PERSON_BASE_URL:https://bc-person.sop.local:9452}

security.enabled=${SECURITY_ENABLED:true}
mtls.enabled=${MTLS_ENABLED:true}

# virtual threads config
common.threads.virtual.enabled=true
common.threads.virtual.tomcat-threads-max=500
common.threads.virtual.max-connections=20000
common.threads.virtual.connection-timeout=30000
