@startuml Common Data Class Diagram
top to bottom direction
title Commmon Data BC Class Diagram
skinparam packageStyle rectangle
skinparam Shadowing false
skinparam classFontSize 12
skinparam classFontName Arial
skinparam WrapWidth 260
skinparam ComponentStyle uml2

folder "local.sop.sopinfo.infrastructure.data" #LightGreen {
    class JpaAutoConfiguration <<AutoConfiguration>> {}
}

@enduml