-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by infra/scripts/gen-ddl.py at 2026-05-18T10:31:08Z
-- Review carefully before applying to a production database.

CREATE TABLE IF NOT EXISTS sop_instructor (
    sop_ref BINARY(16) NOT NULL,
    instructor_ref BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (sop_ref, instructor_ref)
);
